### ISSUE TITLE
异常处理

### ISSUE THREAD

**Issue by terrylakey** [kingschan1204/istock#17]
楼主，启动报这个错
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'tushare.token' in value "${tushare.token}"
	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:172)
	at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:124)
	at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:237)
	at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:211)
	at org.springframework.context.support.PropertySourcesPlaceholderConfigurer.lambda$processProperties$0(PropertySourcesPlaceholderConfigurer.java:175)
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveEmbeddedValue(AbstractBeanFactory.java:839)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1083)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1062)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:581)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:370)
	... 45 common frames omitted

**Comment by kingschan1204** [comment]
1.[点击这个链接注册帐号](https://tushare.pro/register?reg=133400)
2.然后https://tushare.pro/user/token   在这个页面可以拿到token
3.把token复制到application.properties 
![微信截图_20190409152849](https://user-images.githubusercontent.com/4113891/55781105-f8cc7f80-5adb-11e9-83d0-b191fddea24a.png)

![微信截图_20190409152802](https://user-images.githubusercontent.com/4113891/55781065-e4888280-5adb-11e9-8fc9-77a246bff9d0.png)

**Comment by kingschan1204** [comment]
tushare.token=你帐号的token    把这一项加入application.properties

**Comment by terrylakey** [comment]
启动项目如何登录 登录用户的信息在哪里啊

**Comment by kingschan1204** [comment]
istock项目不需要登录的呀。

**Comment by terrylakey** [comment]
> istock项目不需要登录的呀。

我这边启动之后用 127.0.0.1访问弹出一个登录的对话框来
![image](https://user-images.githubusercontent.com/42146879/55784021-42b86400-5ae2-11e9-8756-038c0ef709d7.png)

**Comment by kingschan1204** [comment]
这个是spring boot actuator 开放管理接口 帐号密码是自己设置的。
**1.x分支**

```
management.context-path=/admin
security.user.name=配置的帐号
security.user.password=配置的密码
```
2.x分支配置
```
#actuator端口
management.server.port=80
#修改访问路径  2.0之前默认是/   2.0默认是 /actuator  可以通过这个属性值修改
management.endpoints.web.base-path=/admin
#开放所有页面节点  默认只开启了health、info两个节点
management.endpoints.web.exposure.include=*
management.endpoint.metrics.enable=true
#显示健康具体信息  默认不会显示详细信息
management.endpoint.health.show-details=always
spring.security.user.name=配置的帐号
spring.security.user.password=配置的密码
spring.security.user.roles=SUPERUSER
```
